export const RECORD_ADDRESS = 'RECORD_ADDRESS' // 当前经纬度
export const SAVE_GEOHASH = 'SAVE_GEOHASH' // 当前citygeohash
export const RECORD_USERINFO = 'RECORD_USERINFO'
export const GET_USERINFO = 'GET_USERINFO' // 获取用户信息存入vuex
export const RESET_NAME = 'RESET_NAME' //修改用户名
export const OUT_LOGIN = 'OUT_LOGIN' // 退出登录
export const SAVE_ADDDETAIL = 'SAVE_ADDDETAIL'
export const SAVE_ADDRESS = 'SAVE_ADDRESS' //保存用户地址
export const ADD_ADDRESS = 'ADD_ADDRESS' //添加用户地址